name: publish

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "package.json"
      - "tsconfig.json"
      - ".github/workflows/publish.yml"

permissions:
  contents: write
  id-token: write

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org"

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      - uses: GitTools/actions/gitversion/setup@v4
        with:
          versionSpec: "6.x"

      - id: gitversion
        uses: GitTools/actions/gitversion/execute@v4

      - run: npm version ${{ steps.gitversion.outputs.majorMinorPatch }} --no-git-tag-version
        working-directory: ./src/package
      - run: npm ci
        working-directory: ./src/package
      - run: npm run build
        working-directory: ./src/package
      - run: npm publish --provenance --access public
        working-directory: ./src/package

      - run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git tag v${{ steps.gitversion.outputs.majorMinorPatch  }}
          git push origin v${{ steps.gitversion.outputs.majorMinorPatch }}

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.gitversion.outputs.majorMinorPatch }}
          generate_release_notes: true
